### PR TITLE
Fix for build and run executable for Etlas >= 1.5.0.0

### PR DESCRIPTION
**Pull request by Romastyi**
It is the same pull request as #19 There was something wrong and I have closed the previous one.

### CODE REVIEW

**Comment by rahulmutt** [comment]
This looks good - anymore changes you want to include or should I merge?

**Review by rahulmutt — APPROVED** [review]

**Comment by Romastyi** [comment]
Yes. I have one more change. This one about external dependencies resolving.
I've tried to run project [eta-servant-example](https://github.com/rahulmutt/eta-servant-example) via this `sbt` plugin and got an error:

> Exception in thread "main" java.lang.ClassNotFoundException: org.eclipse.jetty.server.Connector

It happened because `sbt` plugin process as external dependencies only libs which are in section `maven-depends` of `.cabal` file. There is no `maven-depends` section in this project. But some `eta` libs has such dependencies, for example:

> dependency,wai-servlet-handler-jetty,javax.servlet:javax.servlet-api:3.1.0:org.eclipse.jetty:jetty-server:9.4.5.v20170502,/home/romastyi/.etlas/store/eta-0.8.6.5/wai-servlet-handler-jetty-0.1.2.0-f27d7066c58a43f516709ef5c34971e8ba9172cb5951959ffb34769e1db03a22/lib/wai-servlet-handler-jetty-0.1.2.0-f27d7066c58a43f516709ef5c34971e8ba9172cb5951959ffb34769e1db03a22.jar,base:wai:wai-servlet

i.e. library `wai-servlet-handler-jetty` depends of `javax.servlet:javax.servlet-api:3.1.0` and `org.eclipse.jetty:jetty-server:9.4.5.v20170502`.
This change solve this problem and add such external dependencies to `sbt` `libraryDependencies` variable.

**Comment by rahulmutt** [comment]
Wonderful, thanks for doing extensive testing! When you have committed all the necessary fixes, let me know and I'll do a review & merge.

**Comment by Romastyi** [comment]
I added another fix which allows plugin to work with projects with several artifacts. For example, this one: [crud-ex-backend-servant](https://github.com/rpeszek/crud-ex-backend-servant/tree/eta-jetty)

**Comment by Romastyi** [comment]
I think this is the last commit in this pull request.

**Review by rahulmutt — APPROVED** [review]
@Romastyi Thanks for the changes, merging.

**Pull request merged**
