### PR TITLE
#23 Compatibility with `sbt` 0.13.x

### PR DESCRIPTION
**Pull request by Romastyi**
This pull request contains:

- Fix for `Etlas` download problem, which fails CI
- Support for `maven-repos` field in `.cabal` file
- Drop `eta-init` command, only configuration using DSL stayed
- Compatibility with `sbt` 0.13.x

I think that all features from #23 done, isn't it?

### CODE REVIEW

**Review by rahulmutt — APPROVED** [review]
Thanks, it does indeed look like it #23 is done. Next step is just to port all the gradle-eta examples and ensure they work.

**Comment by Romastyi** [comment]
I think, that all of examples are done. The `example-multi` subproject is the port of original `multi` example. The `example` subproject contains all other features in itself: it contains tests like in the `test` example and `assembly` plugin covers functionality of the `fatjar` example. All example projects contains `java/scala` interoperability. Only feature which is not present this is using `CPP` extension like in the original `simple` example.

Do you mean to port directory structure or make division into projects like in `gradle-eta`?

**Comment by rahulmutt** [comment]
Ok in that case, no need for more examples. 

Would you be interested in writing documentation for the SBT plugin features that you've added, similar to [this section](https://eta-lang.org/docs/user-guides/gradle-user-guide)? You need to submit a PR to the main eta repo for the changes.

Here's where the Gradle User Guide is sourced:

https://github.com/typelead/eta/tree/master/docs/0-user-guides/2-gradle-user-guide

**Comment by Romastyi** [comment]
I'll try to write documentation. Can I do this based on `Gradle Guide` just modifying this according `sbt-eta`DSL?

**Comment by rahulmutt** [comment]
That sounds perfect!

**Pull request merged**
