### PR TITLE
Update sbt plugin to work with Etlas >= 1.5.0.0

### LINKED ISSUE #14: --maven flag unrecognised by Eta master
Trying to use this plugin with Eta as of https://github.com/typelead/eta/commit/5546a4ba9f9b71fc2a147ba1bd958fd3ca41740c gives:

```
etlas: unrecognized 'deps' option `--maven'
```

### PR DESCRIPTION
**Pull request by romac**
Fixes #14 #16 #17

### CODE REVIEW

**Comment by romac** [comment]
All this could of course be made more robust and efficient but the couple hours I have spent on it is unfortunately all I can spare at the moment. I hope to come back to it when I have more free time to improve things further, and perhaps address some of the other open issues :)

**Review by rahulmutt — APPROVED** [review]
This is amazing, thank you for working on this @romac! I'll try it out and see if I can do a release.

**Comment by rahulmutt** [comment]
The build failure has nothing to do with your changes, but it seems to be a problem with the CI setup. I'll see if I can utilize the docker image for Eta to fix it.

**Comment by romac** [comment]
> The build failure has nothing to do with your changes, but it seems to be a problem with the CI setup. I'll see if I can utilize the docker image for Eta to fix it.

Oh you merged it already. I was just in the process of updating the `.travis.yaml` script to install `etlas` in `before_script`, as such:

```diff
diff --git a/.travis.yml b/.travis.yml
index d54143a..7763d9f 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,12 @@
 sudo: false
 language: scala
 jdk: oraclejdk8
+
+before_script:
+  - wget "https://cdnverify.eta-lang.org/eta-binaries/etlas-1.5.0.0/binaries/x86_64-linux/etlas"
+  - chmod +x etlas
+  - export PATH=$PATH:$PWD/etlas
+
 script:
-- sbt ^test
-- cd example/ && sbt run
+  - sbt ^test
+  - cd example/ && sbt run
```

I didn't know about the Docker image, so I'll perhaps let you decide how best to fix this.

Cheers :)

**Pull request merged**
