### PR TITLE
#23 Etlas Configuration

### PR DESCRIPTION
**Pull request by Romastyi**
This pull request provides support for Etlas configuration, i.e. downloading of Etlas binary and the custom install path.

### CODE REVIEW

**Comment by rahulmutt** [comment]
Thanks @Romastyi! I think after this we should be done.

Two things:

1) Can you make the eta/etlas configuration global, rather than project-specific?

2) When you download a fresh copy of `etlas` and `~/.etlas/config` is missing, it'll ask you about your metrics preference. There should be some argument or configuration you should be able to send to SBT to convey that preference. In the gradle plugin, we use `etaSendMetrics` property which can be send through command line and configured in a `build.gradle`.

**Comment by Romastyi** [comment]
@rahulmutt All done!

Now Eta/Etlas settings are in `ThisBuild` scope. I think that is enough and it is not necessary to add them to `Global` scope. You can see an example of configuration in `example` subproject.

**Review by rahulmutt — APPROVED** [review]
Thank you so much @Romastyi! I think we've reached feature parity. Are there any other things that you are planning on working on? Otherwise, I can try to cut a release by the end of the week.

**Comment by Romastyi** [comment]
I think, that I'll try to do work about `etlas freeze`.

Anyway, before release a compatibility between `sbt` 0.13.x and 1.x needs to be checked.

**Comment by rahulmutt** [comment]
Sounds good!

**Pull request merged**
