### PR TITLE
Feature parity with the Gradle plugin, DSL #23

### PR DESCRIPTION
**Pull request by Romastyi**
This is the first fully functional version of DSL for configuring Eta projects in `build.sbt `.

This version not contains:
- [x] [Configuring Eta](https://eta-lang.org/docs/user-guides/gradle-user-guide/advanced-configuration/global-configuration#configuring-eta) Can use only `eta` installed in system.
- [x] [Git Dependency](https://eta-lang.org/docs/user-guides/gradle-user-guide/advanced-configuration/dependency-management#git-dependency) Can specify `eta` and `maven` dependencies, but no `git` dependencies.

### CODE REVIEW

**Comment by rahulmutt** [comment]
@Romastyi This looks great! My only concern is that by default, it looks like you're writing the cabal file for a package inside of the `src/main/eta` folder. Can you write it inside of the `target` directory instead? The .cabal file should not be visible to the user since it's generated.

**Comment by Romastyi** [comment]
It was made for compatibility reasons with the older code base. Project layout is described in [README](https://github.com/typelead/sbt-eta#project-layout). If it is not an issue, I can remove _"old layout"_ support.

Anyway I'll move generated `.cabal` into `traget/eta` folder.

**Comment by rahulmutt** [comment]
@Romastyi You can go ahead and make it a breaking change.

**Comment by Romastyi** [comment]
@rahulmutt Done. Now the `.cabal` file will be generated in `target/eta` folder.

**Comment by Romastyi** [comment]
Added support for specifying Eta compiler version. [Gradle plugin](https://eta-lang.org/docs/user-guides/gradle-user-guide/advanced-configuration/global-configuration#configuring-eta)

**Comment by rahulmutt** [comment]
@Romastyi Great work so far! :) will you also be adding support for git dependencies before I merge? It amounts to generating a `cabal.project` along with the `.cabal` file. Let me know if you need more info on what to generate.

**Comment by Romastyi** [comment]
Added support for Git dependencies. Checked in `example` project.

**Comment by Romastyi** [comment]
Examing the functionality of `gradle-eta` plugin I noticed that it writes `cabal.project.freeze` file too, more precisely executes the command `etlas freeze`. Is it important in your opinion?

**Comment by rahulmutt** [comment]
@Romastyi That `cabal.project.freeze` is a different aspect you may want to work on. I'll merge what you have for now and detail that in the feature parity issue.

**Review by rahulmutt — APPROVED** [review]
@Romastyi Great work - we're almost there!

**Pull request merged**
